from .morghi_card import Card


# NUM CONSTANTS
NUM_OF_PLAYERS: int = 4
MAX_NUM_OF_CARDS_IN_HAND: int = 4
MIN_NUM_OF_CARDS_IN_HAND: int = 4
NUM_OF_MORGHS: int = 11
NUM_OF_KHOROSES: int = 11
NUM_OF_ROBAHS: int = 7
NUM_OF_MARS: int = 4
NUM_OF_TALES: int = 6
NUM_OF_LOUNES: int = 11
NUM_OF_TOKHMS: int = 60

# AVAILABLE CARDS IN THE GAME
AVAILABLE_ANIMAL_CARDS={
    "Morgh": NUM_OF_MORGHS, 
    "Khoros": NUM_OF_KHOROSES, 
    "Robah": NUM_OF_ROBAHS, 
    "Mar": NUM_OF_MARS
    }

AVAILABLE_NONANIMAL_CARDS={
    "Loune": NUM_OF_LOUNES, 
    "Tale": NUM_OF_TALES
    }

#AVAILABLE_CARDS = {**AVAILABLE_ANIMAL_CARDS, **AVAILABLE_NONANIMAL_CARDS}

AVAILABLE_CARDS = {
    "animal": AVAILABLE_ANIMAL_CARDS,
    "nonanimal": AVAILABLE_NONANIMAL_CARDS
}

TOTAL_NUM_CARDS=sum(AVAILABLE_CARDS.values())

# Rules 
CARDS_FOR_TOKHM_BEZAR = {"Morgh": 1, "Khoros": 1, "Loune": 1}
CARDS_FOR_JOJOO_BEZAR = {"Morgh": 2}